import type { PaletteSwatch } from "@/lib/types";

export interface PalettePreset {
  id: string;
  label: string;
  description: string;
  swatches: PaletteSwatch[];
}

// 12-season color analysis presets. Each preset ships with 12 swatch starters —
// every user is expected to add/remove/tweak swatches after picking a season.
export const PALETTE_PRESETS: PalettePreset[] = [
  {
    id: "light-spring",
    label: "Light Spring",
    description: "Warm, light, delicate — pastels with a sunny edge.",
    swatches: [
      { name: "Soft cream",     hex: "#F5EBD5" },
      { name: "Light peach",    hex: "#FAD6BC" },
      { name: "Peach blossom",  hex: "#F4C2A1" },
      { name: "Coral pink",     hex: "#F49E8B" },
      { name: "Apricot",        hex: "#E8A57E" },
      { name: "Daffodil",       hex: "#F2D27C" },
      { name: "Soft buttercup", hex: "#F5DD93" },
      { name: "Mint",           hex: "#A8D8B0" },
      { name: "Aqua",           hex: "#8DCCC8" },
      { name: "Periwinkle",     hex: "#9CA8DC" },
      { name: "Warm taupe",     hex: "#C4A88B" },
      { name: "Camel",          hex: "#B89373" },
    ],
  },
  {
    id: "true-spring",
    label: "True Spring",
    description: "Warm, clear, vivid — fresh and saturated.",
    swatches: [
      { name: "Ivory",          hex: "#F4ECD8" },
      { name: "Warm coral",     hex: "#F07A5C" },
      { name: "Bright peach",   hex: "#F59873" },
      { name: "Tomato",         hex: "#E55333" },
      { name: "Marigold",       hex: "#E89B2C" },
      { name: "Golden yellow",  hex: "#F2C44A" },
      { name: "Warm magenta",   hex: "#D44B7B" },
      { name: "Leaf green",     hex: "#7BB85C" },
      { name: "Turquoise",      hex: "#3FB5B0" },
      { name: "Cornflower",     hex: "#6E8FD8" },
      { name: "Warm brown",     hex: "#8B5E3C" },
      { name: "Light camel",    hex: "#C7A578" },
    ],
  },
  {
    id: "bright-spring",
    label: "Bright Spring",
    description: "Warm-ish, bright, high contrast — striking and clear.",
    swatches: [
      { name: "Pure white",     hex: "#FBFAF5" },
      { name: "Hot pink",       hex: "#E84C7D" },
      { name: "Bright coral",   hex: "#F25B4C" },
      { name: "Tangerine",      hex: "#F58028" },
      { name: "Sunflower",      hex: "#FFCB29" },
      { name: "Lime",           hex: "#B8D74A" },
      { name: "Apple green",    hex: "#7CC340" },
      { name: "Emerald",        hex: "#2BA67A" },
      { name: "Turquoise",      hex: "#1FB9C4" },
      { name: "Royal blue",     hex: "#3658D6" },
      { name: "Violet",         hex: "#7A4AD6" },
      { name: "Charcoal",       hex: "#2B2B2B" },
    ],
  },
  {
    id: "light-summer",
    label: "Light Summer",
    description: "Cool, light, soft — airy and watercolour-like.",
    swatches: [
      { name: "Soft white",     hex: "#F2F0EC" },
      { name: "Powder pink",    hex: "#EFC5CA" },
      { name: "Rose",           hex: "#D89BA4" },
      { name: "Cool mauve",     hex: "#C4A6B8" },
      { name: "Lavender",       hex: "#C3B3D6" },
      { name: "Sky blue",       hex: "#A6C9DC" },
      { name: "Periwinkle",     hex: "#8FA3D4" },
      { name: "Seafoam",        hex: "#A8D2C2" },
      { name: "Soft jade",      hex: "#82B8A0" },
      { name: "Slate",          hex: "#7E94A8" },
      { name: "Dove grey",      hex: "#B5B0AA" },
      { name: "Cool taupe",     hex: "#9C8C81" },
    ],
  },
  {
    id: "true-summer",
    label: "True Summer",
    description: "Cool, soft-to-medium, gentle — calm and refined.",
    swatches: [
      { name: "Cool white",     hex: "#EDEEEA" },
      { name: "Rose grey",      hex: "#C9B0B5" },
      { name: "Dusty rose",     hex: "#C68B98" },
      { name: "Raspberry",      hex: "#A8466A" },
      { name: "Plum",           hex: "#6E3F5F" },
      { name: "Dusty blue",     hex: "#8BA3BD" },
      { name: "Soft denim",     hex: "#7A92B0" },
      { name: "Slate blue",     hex: "#5778A6" },
      { name: "Cool teal",      hex: "#3D7B85" },
      { name: "Sage",           hex: "#8FA68C" },
      { name: "Cool grey",      hex: "#94918C" },
      { name: "Charcoal",       hex: "#3E3E45" },
    ],
  },
  {
    id: "soft-summer",
    label: "Soft Summer",
    description: "Cool-ish, soft, muted — quiet, hazy elegance.",
    swatches: [
      { name: "Oat",            hex: "#E0DAC8" },
      { name: "Muted pink",     hex: "#D2B5B8" },
      { name: "Mushroom",       hex: "#A89C8A" },
      { name: "Dusty mauve",    hex: "#A98896" },
      { name: "Smoky rose",     hex: "#B07A82" },
      { name: "Faded plum",     hex: "#6E5364" },
      { name: "Storm blue",     hex: "#506680" },
      { name: "Dusty sage",     hex: "#A8B098" },
      { name: "Sage",           hex: "#92A089" },
      { name: "Deep teal",      hex: "#395E5F" },
      { name: "Cocoa",          hex: "#6E5645" },
      { name: "Soft charcoal",  hex: "#4A4A4A" },
    ],
  },
  {
    id: "soft-autumn",
    label: "Soft Autumn",
    description: "Warm-ish, soft, muted — natural and earthy.",
    swatches: [
      { name: "Cream",          hex: "#EAE0CB" },
      { name: "Dusty gold",     hex: "#C9A86E" },
      { name: "Camel",          hex: "#B89572" },
      { name: "Terracotta",     hex: "#B86F4F" },
      { name: "Rust",           hex: "#9E5436" },
      { name: "Olive",          hex: "#7A7A4A" },
      { name: "Moss",           hex: "#5F6E48" },
      { name: "Sage",           hex: "#94A38A" },
      { name: "Petrol",         hex: "#3C6671" },
      { name: "Warm taupe",     hex: "#A89180" },
      { name: "Rose taupe",     hex: "#A89094" },
      { name: "Cocoa",          hex: "#6B4A36" },
    ],
  },
  {
    id: "true-autumn",
    label: "True Autumn",
    description: "Warm, deep, rich — golden and grounded.",
    swatches: [
      { name: "Warm ivory",     hex: "#EFE2C2" },
      { name: "Mustard",        hex: "#C9942D" },
      { name: "Copper",         hex: "#B86B30" },
      { name: "Pumpkin",        hex: "#C56B2A" },
      { name: "Brick",          hex: "#A0412A" },
      { name: "Dark amber",     hex: "#8E5A1F" },
      { name: "Forest green",   hex: "#3E5E3A" },
      { name: "Teal",           hex: "#2D6A6E" },
      { name: "Chocolate",      hex: "#5C3A22" },
      { name: "Aubergine",      hex: "#5B2A38" },
      { name: "Olive",          hex: "#6E6A2E" },
      { name: "Warm beige",     hex: "#C9A87C" },
    ],
  },
  {
    id: "deep-autumn",
    label: "Deep Autumn",
    description: "Warm-ish, deep, rich — bold spice notes.",
    swatches: [
      { name: "Bone",           hex: "#E2D7BE" },
      { name: "Mustard",        hex: "#A88029" },
      { name: "Burnt orange",   hex: "#B25425" },
      { name: "Rust",           hex: "#8E4222" },
      { name: "Burgundy",       hex: "#6B2A2D" },
      { name: "Deep plum",      hex: "#3E1F36" },
      { name: "Pine",           hex: "#234534" },
      { name: "Inky teal",      hex: "#1F3F47" },
      { name: "Bronze",         hex: "#7A5826" },
      { name: "Olive black",    hex: "#3D3A20" },
      { name: "Espresso",       hex: "#3A2418" },
      { name: "Charcoal",       hex: "#2B2926" },
    ],
  },
  {
    id: "deep-winter",
    label: "Deep Winter",
    description: "Cool-ish, deep, vivid — dramatic and high-contrast.",
    swatches: [
      { name: "Pure white",     hex: "#F8F8F8" },
      { name: "Black",          hex: "#0F0F10" },
      { name: "True red",       hex: "#B5172E" },
      { name: "Wine",           hex: "#5C1A2D" },
      { name: "Magenta",        hex: "#A8265B" },
      { name: "Cool fuchsia",   hex: "#C8348C" },
      { name: "Royal purple",   hex: "#4A2A6E" },
      { name: "Navy",           hex: "#1B2B58" },
      { name: "Deep emerald",   hex: "#1A5C44" },
      { name: "Pine",           hex: "#1F4534" },
      { name: "Ice blue",       hex: "#A8C8E0" },
      { name: "Charcoal",       hex: "#2E2E33" },
    ],
  },
  {
    id: "true-winter",
    label: "True Winter",
    description: "Cool, deep, clear — sharp icy contrast.",
    swatches: [
      { name: "Snow white",     hex: "#FAFAFC" },
      { name: "Black",          hex: "#0A0A0C" },
      { name: "Crimson",        hex: "#B82236" },
      { name: "Cool fuchsia",   hex: "#C92E7E" },
      { name: "Royal blue",     hex: "#1F3FA8" },
      { name: "Cobalt",         hex: "#0F4FB5" },
      { name: "Icy blue",       hex: "#B8DCEC" },
      { name: "Emerald",        hex: "#10744F" },
      { name: "Icy pink",       hex: "#F2C6D2" },
      { name: "Icy lavender",   hex: "#D2C2E4" },
      { name: "Midnight",       hex: "#0E1838" },
      { name: "Charcoal",       hex: "#1F1F24" },
    ],
  },
  {
    id: "bright-winter",
    label: "Bright Winter",
    description: "Cool-ish, bright, clear — electric and luminous.",
    swatches: [
      { name: "Pure white",     hex: "#FBFBFB" },
      { name: "Hot pink",       hex: "#E91E63" },
      { name: "Hot magenta",    hex: "#D81E8F" },
      { name: "Crimson",        hex: "#D8163A" },
      { name: "Bright coral",   hex: "#F35F50" },
      { name: "Lemon",          hex: "#F3D830" },
      { name: "Emerald",        hex: "#12A05F" },
      { name: "Turquoise",      hex: "#1FBCC8" },
      { name: "Ice blue",       hex: "#A8D8E8" },
      { name: "Electric blue",  hex: "#0A4FE0" },
      { name: "Violet",         hex: "#6A2BD8" },
      { name: "Black",          hex: "#101012" },
    ],
  },
];

export function getPaletteById(id: string | null): PalettePreset | undefined {
  if (!id) return undefined;
  return PALETTE_PRESETS.find((p) => p.id === id);
}
